// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.4, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as App$PaceCore from "@pace/core/src/App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$PaceCore.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
